function treeOut = bivariate(leftTree, rightTree, method, type)
% type
%   2: Both treeVars
%   1: Only right treeVar
%   0: Only left treeVar
if ( type == 2 )
    treeOut = struct('method', method, 'numArgs', 2, ...
        'left', leftTree, 'right', rightTree, ...
        'diffOrder', max(leftTree.diffOrder, rightTree.diffOrder), ...
        'ID', leftTree.ID | rightTree.ID, ...
        'height', max(leftTree.height, rightTree.height) + 1);
elseif ( type == 1 )
    treeOut = struct('method', method, 'numArgs', 2, ...
        'left', leftTree, 'right', rightTree, ...
        'diffOrder', rightTree.diffOrder, ...
        'height', rightTree.height + 1, ...
        'ID', rightTree.ID);
else
    treeOut = struct('method', method, 'numArgs', 2, ...
        'left', leftTree, 'right', rightTree, ...
        'diffOrder', leftTree.diffOrder, ...
        'height', leftTree.height + 1, ...
        'ID', leftTree.ID);
end
end