function treeOut = univariate(treeIn, method)
% Construct a syntax tree for univariate functions.
treeOut = struct('method', method, ...
    'numArgs', 1, 'center', treeIn, ...
    'diffOrder', treeIn.diffOrder, ...
    'height', treeIn.height + 1, ...
    'multCoeff', 1, ...
    'ID', treeIn.ID);
end