function handles = setupPanels(handles)
%SETUPPANELS    Populate the panels on CHEBGUI

% Background colour for text fields:
textBackgroundColour = get(handles.panel_input, 'BackgroundColor');
textFontsize = 12;
textHeight = 0.05;

% Create strings above input boxes:
handles.text_DEs = uicontrol('Parent', handles.panel_input, ...
    'Style', 'text', 'BackgroundColor', textBackgroundColour, ...
    'String','Differential equation(s)', 'FontSize', textFontsize, ...
    'Units', 'normalized', 'Position', [0 0.825 1 textHeight]) ;
handles.text_BCs = uicontrol('Parent', handles.panel_input, ...
    'Style', 'text', 'BackgroundColor', textBackgroundColour, ...
    'String','Boundary condition(s)', 'FontSize', textFontsize, ...
    'Units', 'normalized', 'Position', [0 0.495 1 textHeight]) ;
handles.text_LBCs = uicontrol('Parent', handles.panel_input, ...
    'Style', 'text', 'BackgroundColor', textBackgroundColour, ...
    'String','Left boundary condition(s)', 'FontSize', textFontsize, ...
    'Units', 'normalized', 'Position', [0 0.52 1 textHeight]) ;
handles.text_RBCs = uicontrol('Parent', handles.panel_input, ...
    'Style', 'text', 'BackgroundColor', textBackgroundColour, ...
    'String','Right boundary condition(s)', 'FontSize', textFontsize, ...
    'Units', 'normalized', 'Position', [0 0.39 1 textHeight]) ;
handles.text_initial = uicontrol('Parent', handles.panel_input, ...
    'Style', 'text', 'BackgroundColor', textBackgroundColour, ...
    'String','Initial condition', 'FontSize', textFontsize, ...
    'Units', 'normalized', 'Position', [0 0.25 1 textHeight]) ;

% Create a toggle button for whether the latest solution should be used as an
% initial guess:
handles.toggle_useLatest = uicontrol('Parent', handles.panel_input, ...
    'Style', 'togglebutton', ...
    'String','Use latest solution as initial guess', ...
    'FontSize', 12, 'Enable', 'off', ...
    'Callback', @(hObject, eventdata) ...
        toggleUseLatestCallback(hObject, guidata(hObject)), ...
    'Units', 'normalized', 'Position', [0.1 0.025 0.8 0.075]) ;

end

function toggleUseLatestCallback(hObject, handles)
% Called when user toggles between using the latest solution as an initial
% guess.

% Which state is the button in?
newVal = get(hObject, 'Value');

if ( newVal ) % User wants to use latest solution
    set(handles.input_GUESS, 'String', 'Using latest solution');
else
    set(handles.input_GUESS, 'String', '');
    set(handles.input_GUESS, 'Enable', 'On');
    handles.guifile.init = '';
end

guidata(hObject, handles);

end