function handles = setupPanelIVPsolver(handles)
%SETUPPANELS    Populate the panels on CHEBGUI

% Background colour for text fields:
textBackgroundColour = get(handles.panel_buttons, 'BackgroundColor');
textFontsize = 12;
leftMargin = 0.025;
textHeight = 0.45;
vertLoc = linspace(.6,.05, 2);

set(handles.panel_type,'Visible', 'off');
% Create a panel for the problem type option:
handles.panel_IVPsolver = uipanel('Parent', handles.panel_buttons, ...
    'Title', 'IVP solver', 'BackgroundColor', textBackgroundColour, ...
    'Position', [0.045 .63 .92 .135], 'FontSize', textFontsize, ...
    'BorderType', 'etchedin');

% Create strings above input boxes:
handles.button_timestepping = uicontrol('Parent', handles.panel_IVPsolver, ...
    'Style', 'radiobutton', 'BackgroundColor', textBackgroundColour, ...
    'String','Stepping', 'FontSize', textFontsize, ...
    'Callback', @(hObject, eventdata) ...
        switchModeButtonCallback(hObject, guidata(hObject), 'bvp'), ...
    'Units', 'normalized', ...
    'Position', [leftMargin vertLoc(1) 1-leftMargin textHeight]);
handles.button_global = uicontrol('Parent', handles.panel_IVPsolver, ...
    'Style', 'radiobutton', 'BackgroundColor', textBackgroundColour, ...
    'String','Global', 'FontSize', textFontsize, ...
    'Callback', @(hObject, eventdata) ...
        switchModeButtonCallback(hObject, guidata(hObject), 'ivp'), ...
    'Units', 'normalized', ...
    'Position', [leftMargin vertLoc(2) 1-leftMargin textHeight]);
end

function switchModeButtonCallback(hObject, handles, newMode)
% Called when user presses one of the mode changing buttons.
handles = chebguiController.switchMode(handles, newMode);
guidata(hObject, handles);
end